import { test, expect } from "@playwright/test"

test("test", async ({ page }) => {
  // Recording...
  await page.goto("https://www.saucedemo.com/")
  await page.locator('[data-test="username"]').click()
  await page.locator('[data-test="username"]').fill("test_user")
  await page.locator('[data-test="username"]').press("Tab")
  await page.locator('[data-test="password"]').fill("secret_sauce")
  await page.locator('[data-test="login-button"]').click()
  await page.locator("svg").first().click()
  await page.locator('[data-test="username"]').click()
  await page.locator('[data-test="username"]').dblclick()
  await page.locator('[data-test="username"]').fill("standard_user")
  await page.locator('[data-test="login-button"]').click()
  await page
    .locator('[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]')
    .click()
  await page.locator('[data-test="add-to-cart-sauce-labs-onesie"]').click()
  await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click()
  await page.getByText("Name (A to Z)Name (A to Z)").click()
  await page
    .locator('[data-test="product-sort-container"]')
    .selectOption("lohi")
  await page
    .locator('[data-test="primary-header"] div')
    .filter({ hasText: "Swag Labs" })
    .first()
    .click()
  await page.goto("https://www.saucedemo.com/inventory.html")
  await page.getByRole("button", { name: "Open Menu" }).click()
  await page.locator('[data-test="shopping-cart-link"]').click()
  await page.locator('[data-test="remove-sauce-labs-backpack"]').click()
  await page.getByText("$15.99Remove").click()
  await page
    .locator('[data-test="cart-list"] div')
    .filter({ hasText: "1Sauce Labs OnesieRib snap" })
    .locator('[data-test="item-quantity"]')
    .dblclick()
  await page.getByText("Rib snap infant onesie for").click()
  await page.getByText("1Sauce Labs OnesieRib snap").click()
  await page
    .locator('[data-test="cart-list"] div')
    .filter({ hasText: "1Sauce Labs OnesieRib snap" })
    .locator('[data-test="item-quantity"]')
    .dblclick()
  await page.locator('[data-test="checkout"]').click()
  await page.locator('[data-test="firstName"]').click()
  await page.locator('[data-test="firstName"]').fill("Test name")
  await page.locator('[data-test="firstName"]').press("Tab")
  await page.locator('[data-test="lastName"]').fill("test last name")
  await page.locator('[data-test="lastName"]').press("Tab")
  await page.locator('[data-test="postalCode"]').fill("02446")
  await page.locator('[data-test="continue"]').click()
  await page.locator('[data-test="total-label"]').click()
  await page.locator('[data-test="finish"]').click()
  await page.locator('[data-test="back-to-products"]').click()
  await page.getByRole("button", { name: "Open Menu" }).click()
  await page.locator('[data-test="reset-sidebar-link"]').click()
  await page.locator('[data-test="logout-sidebar-link"]').click()
})
